### ISSUE TITLE
hey drizer

### ISSUE THREAD

**Issue by sthefanoss** [dr11z3r/dr11z3r#1]
Are you the same guy from Habbo BR? That from BUGS group?!

It would be nice if so. I was called ShadeBlack at the time.

**Comment by dr11z3r** [comment]
sim senhor

**Comment by sthefanoss** [comment]
ba que loco, me add ai se quiser https://www.linkedin.com/in/sthefanoss/

virei desenvolvedor mobile depois de todo esse tempo, e foi bem legal ter tido aquele contato inicial com a programação na época
